// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ6pnDzTfmW4XqfllZZSWQ2NDvmRNdBLI',
    appId: '1:774138808394:web:a860cd71bb2494f424beb3',
    messagingSenderId: '774138808394',
    projectId: 'macanudos-notes-a435e',
    authDomain: 'macanudos-notes-a435e.firebaseapp.com',
    storageBucket: 'macanudos-notes-a435e.firebasestorage.app',
    measurementId: 'G-YSHSR2SCHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM1osumnmlUJGnGw3pYux-56QrdL0fVZs',
    appId: '1:774138808394:android:d41efb21b60d073c24beb3',
    messagingSenderId: '774138808394',
    projectId: 'macanudos-notes-a435e',
    storageBucket: 'macanudos-notes-a435e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ6pnDzTfmW4XqfllZZSWQ2NDvmRNdBLI',
    appId: '1:774138808394:web:0162fcdfcf224b0a24beb3',
    messagingSenderId: '774138808394',
    projectId: 'macanudos-notes-a435e',
    authDomain: 'macanudos-notes-a435e.firebaseapp.com',
    storageBucket: 'macanudos-notes-a435e.firebasestorage.app',
    measurementId: 'G-5PSTGF3F2G',
  );
}
